stages:
  fetch_data:
    cmd: python src_versioning/data_preprocess.py --output data/raw/gold_snapshot_latest.csv
    deps:
      - src_versioning/data_preprocess.py
    outs:
      - data/raw/gold_snapshot_latest.csv

  train_model:
    cmd: python src_versioning/train_model.py --input data/raw/gold_snapshot_latest.csv --output models/gold_lstm_model.keras
    deps:
      - src_versioning/train_model.py
      - data/raw/gold_snapshot_latest.csv
    outs:
      - models/gold_lstm_model.keras
      
  update_metadata:
    cmd: python src_versioning/metadata_updater.py 
    deps:
      - src_versioning/metadata_updater.py
      - models/gold_lstm_model.keras
    outs:
      - metadata/metadata.json
