stages:
  fetch_data:
    cmd: python src_versioning/data_preprocess.py --output data/raw/gold_snapshot_latest.csv
    deps:
      - src_versioning/data_preprocess.py
    outs:
      - data/raw/gold_snapshot_latest.csv

  validate_data:
    cmd: great_expectations checkpoint run gold_prices_checkpoint1
    deps:
      - data/raw/gold_snapshot_latest.csv
      - great_expectations/expectations/Gold_Prices_Suite.json
      - great_expectations/checkpoints/gold_prices_checkpoint1.yml
    outs:
      - great_expectations/uncommitted/validations/
      - great_expectations/uncommitted/data_docs/local_site/

  train_model:
    cmd: python src_versioning/train_model.py --input data/raw/gold_snapshot_latest.csv --output models/gold_lstm_model.pkl
    deps:
      - src_versioning/train_model.py
      - data/raw/gold_snapshot_latest.csv
    outs:
      - models/gold_lstm_model.pkl

  update_metadata:
    cmd: python src_versioning/metadata_updater.py
    deps:
      - src_versioning/metadata_updater.py
      - models/gold_lstm_model.pkl
    outs:
      - models/model_metadata.json

  drift_detection:
    cmd: python src_versioning/drift_detector.py --reference data/reporting_data/base_data.parquet --current data/raw/gold_snapshot_latest.csv --out data/reporting_data/drift_report.html
    deps:
      - src_versioning/drift_detector.py
      - data/reporting_data/base_data.parquet
      - data/raw/gold_snapshot_latest.csv
    outs:
      - data/reporting_data/drift_full_report.html
      - data/reporting_data/drift_test_suite_report.html