stages:
  fetch_data:
    cmd: python src_versioning/fetch_data.py --output data/raw/gold_snapshot_latest.csv
    deps:
      - src_versioning/fetch_data.py
    outs:
      - path: data/raw/gold_snapshot_latest.csv
        persist: true

  train_model:
    cmd: python src_versioning/train_model.py --input data/raw/gold_snapshot_latest.csv --output models/gold_lstm_model.keras
    deps:
      - src_versioning/train_model.py
      - data/raw/gold_snapshot_latest.csv
    outs:
      - path: models/gold_lstm_model.keras
        persist: true